import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { renderGuide } from './guide.mjs';
const root = dirname(fileURLToPath(import.meta.url));
const project = resolve(root, '..');
const data = JSON.parse(readFileSync(resolve(root, 'content.json'), 'utf8'));
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const base = `https://github.com/qufei1993/skills-hub/blob/${data.revision}/`;
const link = (path, label='查看固定版本依据') => `<a href="${base}${path}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const nav = [['summary','一图看懂'],['crud','增删改查'],['usage','如何使用'],['value','对你的意义'],['scenarios','使用场景'],['architecture','底层原理'],['extensions','扩展方向'],['capabilities','能力明细'],['sources','研究依据']];
const guide = renderGuide(link);
const cards = data.groups.map(g=>`<div class="group"><div class="group-head"><h3>${g.name}</h3><p>${g.note}</p></div><div class="cards">${data.capabilities.filter(c=>c.group===g.id).map(c=>`<article class="card" id="${c.id}"><div class="card-top"><span class="id">${c.id}</span><span class="badge ${c.evidence==='文档描述'?'doc':''}">${c.evidence}</span></div><h3>${c.title}</h3><p>${c.body}</p><div class="outcome"><b>预期结果</b>${c.result}</div><details><summary>使用边界与依据</summary><p>${c.boundary}</p>${link(c.source)}</details></article>`).join('')}</div></div>`).join('');
const scenarios = data.scenarios.map((s,i)=>`<article class="scenario"><span class="who">0${i+1} / ${s.who}</span><h3>${s.title}</h3><p>${s.problem}</p><p class="steps">${s.steps}</p><p><strong>价值：</strong>${s.result}</p><details><summary>适用条件</summary><p>${s.boundary}</p></details><div class="related">相关能力 ${s.capabilities.map(c=>`<a href="#${c}">${c}</a>`).join('')}</div></article>`).join('');
const extensions = data.extensions.map(e=>`<article class="extension"><span>${e.priority}</span><div><h3>${e.title}</h3><p>${e.existing}</p><small>扩展入口：${e.entry}</small></div><div class="proposal"><span class="label">建议增加</span><p>${e.next}</p><small>价值：${e.value}</small></div></article>`).join('');
const sources = [['README.md','项目定位与功能说明'],['package.json','前端与版本配置'],['src-tauri/Cargo.toml','Rust 与桌面依赖'],['src-tauri/src/core/installer.rs','安装、来源与更新'],['src-tauri/src/core/skill_store.rs','SQLite 管理模型'],['src-tauri/src/core/tool_adapters/mod.rs','工具目录与适配规则'],['src-tauri/src/core/sync_engine.rs','链接、复制与冲突保护'],['src-tauri/src/core/system_scheduler.rs','系统调度入口'],['src-tauri/src/core/device_sync/manifest.rs','可移植同步清单'],['src-tauri/src/core/device_sync/merge.rs','三方状态与合并计划'],['src-tauri/src/cli/args.rs','CLI 命令与 JSON 开关'],['LICENSE','MIT 许可证']];
const head = (n,title,note)=>`<div class="section-head"><div><span class="section-number">${n}</span><h2>${title}</h2></div><p>${note}</p></div>`;
const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skills Hub · 能力研究 | 005</title><meta name="description" content="一张图理解 Skills Hub：外部技能接入、增删改查、配套管理 Skill 与多工具分发。附使用场景、上手步骤、原理、扩展方向和个人采用价值。"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23122d38'/%3E%3Cpath d='M8 9h16M8 16h16M8 23h10' stroke='%2399d5c9' stroke-width='3'/%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"></head>
<body><a class="skip" href="#main">跳到正文</a><aside class="sidebar"><a class="brand" href="#main"><span class="mark" aria-hidden="true">S</span>Skills Hub</a><p class="series">开源项目研究 / 005</p><nav aria-label="研究章节">${nav.map(([id,name],i)=>`<a href="#${id}"><span>0${i+1}</span>${name}</a>`).join('')}</nav><div class="side-bottom"><p>固定版本研究<br>2026.09.29 · v${data.version}</p><a href="https://github.com/qufei1993/skills-hub" target="_blank" rel="noopener noreferrer">访问原始仓库</a><p>研究整理页面<br>非 Skills Hub 官方产品</p></div></aside>
<main id="main"><div class="topbar"><span>研究集 / 005 / Skill 管理工具</span><span>固定版本 ${data.version} · ${data.revision.slice(0,7)}</span></div><div class="simple-intro"><span class="eyebrow">先理解它是什么</span><h1>Skills Hub<span>管理 Skill 的工具：接入、增删改查与分发。</span></h1><p class="intro">把多个外部 Skill 汇总到一个本地管理中心。你可以直接用桌面界面，也可以让 AI 通过附带的管理 Skill 帮你操作。</p></div>
${guide.summary}
${guide.crud}
${guide.usage}
${guide.value}
<section id="scenarios">${head('05 / SCENARIOS','放到真实工作中理解','以下场景为基于已知能力的应用分析。')}<div class="scenarios">${scenarios}</div></section>
<section id="architecture">${head('06 / ARCHITECTURE','从一份技能，到多个工具','核心机制：文件 + SQLite + 目录适配 + 同步策略。')}<div class="architecture"><h3>技能内容经过哪些环节？</h3><p>一个 Skill 通常包含 SKILL.md，以及脚本、模板或参考资料。Hub 管理这些内容，下游 AI 工具负责读取并执行任务。</p><div class="flow"><article><span>01 / 获取</span><h3>Git · 本地 · 搜索</h3><p>选择技能目录<br>读取名称与描述</p></article><article><span>02 / 归集</span><h3>中心技能库</h3><p>默认 ~/.skillshub<br>SQLite 记录来源与目标</p></article><article><span>03 / 分发</span><h3>链接或复制</h3><p>适配工具目录<br>选择全局或项目范围</p></article><article><span>04 / 使用</span><h3>目标 AI 工具</h3><p>发现并读取技能<br>按宿主能力执行任务</p></article></div><p class="tech">桌面：React + TypeScript + Tauri　｜　核心：Rust　｜　管理数据：SQLite　｜　设备间：Git 仓库</p></div><div class="principles"><article><h3>内容和配置分开存</h3><p>文件系统保存技能正文和资源；SQLite 记录来源、版本、路径、目标、标签和状态。中心目录是一份内容库，不必等同于一个 Git 工作区。</p>${link('src-tauri/src/core/skill_store.rs','依据：SkillStore 数据模型')}</article><article><h3>链接优先，必要时复制</h3><p>自动模式先尝试符号链接，Windows 可尝试 junction，失败再回退到复制。固定版本对 Cursor 采用复制策略。链接共享文件，副本需要重新同步。</p>${link('src-tauri/src/core/sync_engine.rs','依据：同步引擎')} · ${link('README.md','兼容说明')}</article><article><h3>更新来源 ≠ 同步设备</h3><p>来源更新把上游新内容带入中心库；设备同步交换各电脑上的可移植内容。同步清单保留描述、标签与文件哈希，剥离本地来源路径；合并比较基线、本地和远端。</p>${link('src-tauri/src/core/device_sync/manifest.rs','依据：同步清单')} · ${link('src-tauri/src/core/device_sync/merge.rs','合并计划')}</article><article><h3>AI 管理通过命令行落地</h3><p>宿主 AI 阅读管理 Skill，再调用 skillshub-cli。命令行支持 JSON 输出；它提供管理入口，通用对话与推理由宿主 AI 承担。</p>${link('src-tauri/src/cli/args.rs','依据：CLI 命令定义')}</article></div></section>
<section id="boundaries">${head('采用边界','什么时候值得采用','区分管理能力、执行能力与企业治理。')}<div class="table-wrap" role="region" aria-label="采用边界对照" tabindex="0"><table><thead><tr><th scope="col">你需要的结果</th><th scope="col">当前能提供</th><th scope="col">仍需额外完成</th></tr></thead><tbody><tr><td>多个工具共享技能</td><td>目录分发、来源记录与更新</td><td>逐个工具验证触发与执行效果</td></tr><tr><td>项目专用工作方法</td><td>项目目标和启用状态配置</td><td>检查技能依赖、权限与规范冲突</td></tr><tr><td>多电脑内容一致</td><td>Git 同步、历史和冲突处理</td><td>配置每台设备的路径、目标与凭据</td></tr><tr><td>团队统一技能版本</td><td>共享来源和已有管理机制</td><td>补充版本策略、发布审批和审计</td></tr></tbody></table></div><p class="recommendation"><strong>采用判断：</strong>工具、技能、项目或设备越多，集中管理越有价值。只有一个工具和少量稳定技能时，手动管理也可能足够。同步成功不能替代任务效果验证。</p></section>
<section id="extensions">${head('07 / OPPORTUNITIES','从个人整理，走向可靠协作','分析建议 · 非已实现功能或官方路线图')}<div class="extensions">${extensions}</div><p class="recommendation">建议优先顺序：版本与可复现性 → 兼容性和效果评估 → 团队治理。CLI 已经存在，进一步扩展应建立在现有能力上。</p></section>
<section id="capabilities">${head('08 / CAPABILITIES','14 项能力明细','点击卡片底部，查看边界和固定版本依据。')}${cards}</section>
<section id="sources">${head('09 / EVIDENCE','每项结论，都能回到依据','研究快照 · 2026-09-29')}<div class="sources"><p><strong>固定提交：</strong><code>${data.revision}</code><br><strong>版本标识：</strong>package.json 与 Cargo.toml 均为 ${data.version}；未核验该提交对应的安装包发布状态。</p><p><strong>文档描述</strong>：上游声明的功能。<strong>代码核验</strong>：已阅读相应实现，未运行验证。<strong>分析建议</strong>：研究者推导的场景、边界与扩展方向。</p><p>本次未安装上游应用、运行技能、连接账号或验证跨平台兼容性。Linux 在上游说明中仍标注未做本地验证。网页中的流程为研究示意，不是实时同步状态。</p><ul class="source-list">${sources.map(([path,label])=>`<li>${link(path,label)}</li>`).join('')}</ul></div></section><footer><span>005 · Skills Hub / 中文研究与展示<br>上游源码采用 MIT 许可；本页面为独立研究。</span>${link('README.md','阅读上游说明')}</footer></main></body></html>`;
writeFileSync(resolve(root,'index.html'),html);
const out = resolve(project,'../../site/005-skills-hub');
mkdirSync(out,{recursive:true});
for(const file of ['index.html','styles.css','summary.svg']) copyFileSync(resolve(root,file),resolve(out,file));
copyFileSync(resolve(root,'summary.svg'),resolve(project,'assets/capability-summary.svg'));
const md = `# Skills Hub · 14 项能力清单\n\n固定提交：\`${data.revision}\`。由 web/content.json 统一生成；代码核验不表示运行实测。\n\n` + data.groups.map(g=>`## ${g.name}\n\n${g.note}\n\n`+data.capabilities.filter(c=>c.group===g.id).map(c=>`### ${c.id} · ${c.title}\n\n${c.body}\n\n- 预期结果：${c.result}\n- 使用边界：${c.boundary}\n- 证据等级：${c.evidence}\n- [固定版本依据](${base}${c.source})\n`).join('\n')).join('\n');
writeFileSync(resolve(project,'CAPABILITIES.md'),md);
writeFileSync(resolve(project,'SCENARIOS.md'),'# Skills Hub · 使用场景\n\n以下为基于已知功能的应用分析，不代表实测效果。\n\n'+data.scenarios.map(s=>`## ${s.title}\n\n- 面向：${s.who}\n- 问题：${s.problem}\n- 流程：${s.steps}\n- 预期价值：${s.result}\n- 边界：${s.boundary}\n- 对应能力：${s.capabilities.join('、')}（见 [能力清单](CAPABILITIES.md)）\n`).join('\n'));
writeFileSync(resolve(project,'EXTENSIONS.md'),'# Skills Hub · 扩展方向\n\n以下为研究建议，不是已实现功能或官方路线图。\n\n'+data.extensions.map(e=>`## ${e.priority} · ${e.title}\n\n- 现有基础：${e.existing}\n- 建议增加：${e.next}\n- 预期价值：${e.value}\n- 扩展入口：${e.entry}\n`).join('\n'));
console.log(`Built ${data.capabilities.length} capabilities, ${data.scenarios.length} scenarios, ${data.extensions.length} proposals. Output: ${out}`);
