import fs from 'node:fs';
import path from 'node:path';
import {topics,scenarios} from './overview-model.mjs';
import {classify} from './atlas-model.mjs';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#315fb4','#247a73','#8551a2','#a16827'];
const wrap=(value,max)=>{let rows=[],line='',w=0;for(const c of value){const n=c.charCodeAt(0)>255?1:.56;if(w+n>max){rows.push(line);line='';w=0;}line+=c;w+=n;}if(line)rows.push(line);return rows;};
const text=(x,y,value,size=22,color='#243b57',max=99)=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}">${wrap(value,max).map((v,i)=>`<tspan x="${x}" dy="${i?size*1.35:0}">${esc(v)}</tspan>`).join('')}</text>`;
export function buildOverview(data,root){
 const byName=new Map(data.catalog.map(e=>[e.name,e]));
 for(const name of [...topics.map(t=>t.example),...scenarios.flatMap(s=>s.names)])if(!byName.has(name))throw new Error(`Summary example absent: ${name}`);
 const counts=Object.fromEntries(topics.map(t=>[t.id,data.catalog.filter(e=>classify(e).domain===t.id).length]));
 const source=`https://github.com/VoltAgent/awesome-agent-skills/blob/${data.commit}/README.md`;
 const exampleLink=(name,label)=>`<a href="./catalog.html?q=${encodeURIComponent(name)}">${esc(label||name)}</a>`;
 const cards=topics.map((t,i)=>`<article class="cap-card" style="--accent:${colors[i%4]}"><div class="cap-top"><span>${String(i+1).padStart(2,'0')}</span><small>${counts[t.id]} 个目录条目</small></div><h3>${t.title}</h3><p class="cap-action">${t.action}</p><p class="cap-result"><span>预期产物</span>${t.result}</p><p class="cap-when"><span>何时用</span>${t.when}</p><div class="cap-example">代表技能 ${exampleLink(t.example,t.example.split('/').slice(1).join('/'))}</div></article>`).join('');
 const scenarioCards=scenarios.map((s,i)=>`<article class="scenario"><div class="scenario-index">0${i+1}</div><div class="scenario-content"><span class="scenario-tag">${s.tag}</span><h3>${s.title}</h3><p class="scenario-input">${s.input}</p><div class="chain">${s.chain.map((c,j)=>`${j?'<span aria-hidden="true">→</span>':''}<b>${c}</b>`).join('')}</div><p class="scenario-output">${s.output}</p><p class="scenario-check">验收：${s.check}</p><p class="scenario-links">可查的具体技能：${s.names.map(n=>exampleLink(n,n.split('/').slice(1).join('/'))).join(' · ')}</p></div></article>`).join('');
 const svgParts=[`<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="1550" viewBox="0 0 1440 1550" role="img" aria-labelledby="title desc"><title id="title">Awesome Agent Skills 能力摘要</title><desc id="desc">一个发现与筛选外部技能的目录。20 个方向分别展示能力、预期产物和使用时机，覆盖全部 1108 个目录条目。</desc><style>text{font-family:Microsoft YaHei,Segoe UI,Arial,sans-serif}</style><rect width="1440" height="1550" fill="#f3f6fb"/>`,text(40,65,'Awesome Agent Skills · 能力摘要',40,'#183350'),text(40,115,'它提供技能发现入口，让 AI 助手结合方法、工具与服务完成具体任务。',25),text(40,155,`${data.catalog.length.toLocaleString()} 个目录条目 · 20 个研究方向 · 中文能力说明 · 版本 ${data.commit.slice(0,7)}`,20,'#617590')];
 svgParts.push('<rect x="40" y="183" width="1360" height="79" rx="12" fill="#183350"/>',text(62,216,'你的使用顺序',17,'#b9cdec'),text(240,231,'发现项目 → 理解能力 → 制作原型 → 验证质量 → 发布成果 → 沉淀流程',27,'#ffffff'));
 topics.forEach((t,i)=>{const x=40+(i%4)*344,y=289+Math.floor(i/4)*221,c=colors[i%4];svgParts.push(`<g><rect x="${x}" y="${y}" width="328" height="205" rx="12" fill="#fff" stroke="#dbe3ef"/><rect x="${x+16}" y="${y+18}" width="4" height="27" rx="2" fill="${c}"/>`,text(x+29,y+40,t.title,23,c),text(x+17,y+79,t.action,20,'#334d6b',14.5),text(x+17,y+126,'产物 · '+t.result,19,'#183350',15.5),text(x+17,y+178,'用时 · '+t.when,17,'#637891',17.2),'</g>');});
 svgParts.push(text(40,1442,'对你当前的意义：研究新库时查能力，做演示时找实现方法，交付时补测试，重复工作时沉淀自己的技能。',21),text(40,1483,'说明：这是外部技能目录；实际效果依赖选中的技能、宿主工具、输入与验收。场景为研究归纳，技能运行效果未实测。',17,'#718098'),text(40,1519,'口径：覆盖固定快照全部目录入口，含单项技能与技能集合，集合内部未递归展开。研究快照：2026-09-29。',17,'#718098'),'</svg>');
 const svg=svgParts.join('');
 const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Awesome Agent Skills 中文研究：这个库提供什么、20 类技能能产出什么，以及何时用于开源研究、网页演示、交付和自动化。"><title>Awesome Agent Skills：能力、效果与我的使用场景</title><link rel="icon" href="data:,"><link rel="stylesheet" href="./overview.css"></head><body>
<header class="nav"><a class="brand" href="../"><span>▦</span>开源项目研究 <small>001</small></a><nav aria-label="研究入口"><a class="active" href="./index.html">能力摘要</a><a href="./catalog.html">中文技能目录</a><a href="./atlas.html">全量地图</a><a href="${source}" target="_blank" rel="noopener">原始仓库 ↗</a></nav></header>
<main><section class="hero"><div class="eyebrow">VoltAgent / awesome-agent-skills</div><h1>给 AI 助手找对方法，<br><em>把任务变成具体产物。</em></h1><p class="lead">这是一个汇集<strong>外部技能与技能集合</strong>的开源目录，帮助你找到文档、开发、设计、数据、自动化等任务的方法和工具入口。选中的技能为 AI 助手提供步骤、规则及资源，由助手结合实际工具完成工作。</p><div class="hero-actions"><a class="primary" href="#capabilities">直接看 20 类能力 ↓</a><a href="#my-scenes">我在什么情况下用它 ↗</a></div><div class="facts"><div><strong>1,108</strong><span>已收录目录条目 · 全部中文</span></div><div><strong>20</strong><span>按任务归纳的能力方向</span></div><div><strong>40</strong><span>代表技能的深入解读</span></div><p>固定快照 ed106e8<br>研究日期 2026.09.29</p></div></section>

<section class="capabilities" id="capabilities"><div class="section-heading"><div><span class="eyebrow">能力摘要图</span><h2>按你想得到的成果，找到对应能力。</h2><p>能力、预期产物和使用时机直接展开。无需点击、放大或悬停才能阅读。</p></div><a class="outline" href="./summary.svg" download="awesome-agent-skills-summary.svg">↓ 下载摘要图</a></div><div class="cap-grid">${cards}</div><p class="scope-note">分类为研究归纳，每条只计入一个主方向。部分入口是技能集合，1,108 不是独立技能数量；上面的产物是使用相关技能时的预期结果，尚未运行实测。<a href="${source}" target="_blank" rel="noopener">查看来源</a></p></section>
<section class="value-strip" aria-label="从库到结果"><div><span>库提供什么</span><b>技能发现与筛选入口</b><p>把分散在不同作者仓库中的方法集中起来。</p></div><i>→</i><div><span>技能补充什么</span><b>步骤、规则、脚本与参考</b><p>让助手知道具体任务如何做、怎样检查。</p></div><i>→</i><div><span>最终可能得到什么</span><b>文件、代码、数据与工作流</b><p>取决于所选技能、实际工具与验收标准。</p></div></section>
<section id="my-scenes" class="my-scenes"><div class="section-heading"><div><span class="eyebrow">联系你正在做的事</span><h2>什么时候，你会真正用到它？</h2><p>依据当前的开源项目研究与网页展示工作，从这些具体任务开始选择技能。</p></div></div><div class="scenarios">${scenarioCards}</div></section>
<section class="extension"><div><span class="eyebrow">后续如何形成自己的能力</span><h2>从查一次目录，走向可复用的工作方法。</h2><p>当前优先关注搜索、文档、设计、前端和测试；开始做真实产品时补充后端、数据与运行保障；专业领域按具体选题采用。</p></div><ol><li><b>选择少量任务试用</b><span>围绕要交付的东西选技能，并记录输入、结果和问题。</span></li><li><b>接入自己的资料与模板</b><span>加入项目笔记、设计规范和文档模板，让输出更贴合你。</span></li><li><b>组合已验证的步骤</b><span>把研究、整理、制作和发布连成流程，保留来源与验收。</span></li><li><b>沉淀成个人技能包</b><span>将稳定的方法写成技能，用典型样例持续评估和改进。</span></li></ol></section>
<section class="mechanism"><h2>我们对它的理解</h2><div class="understanding"><article><span>01</span><h3>目录负责发现，技能负责方法</h3><p>这个仓库集中维护链接与简介；外链技能通过说明文件、脚本和资源补充特定任务的方法。宿主助手负责加载和调用工具。</p></article><article><span>02</span><h3>产物可以具体，效果需要验收</h3><p>可以把目标定为“生成报告”“验证网页流程”或“排查故障”。提效比例、业务收益和正确性需要在你的任务中验证。</p></article><article><span>03</span><h3>摘要图用来理解，全量图用来查询</h3><p>本页摘要无需操作即可阅读。完整 SVG 记录全部目录入口；交互网页增加了缩放、搜索和详情。摘要 SVG 可以直接嵌入 README。</p></article></div></section>
<section class="deep-links"><div><h2>需要看到具体技能？</h2><p>查看全部中文简介、代表技能解读，或进入可缩放的完整目录。</p></div><a href="./catalog.html">查看 1,108 项中文目录 →</a><a href="./atlas.html">打开全量地图 →</a></section>
<section class="sources"><h2>资料与证据</h2><p>依据固定版本目录、代表技能说明和 Agent Skills 格式规范整理。全部目录简介已译为中文，英文可在详情中展开；场景和个人价值为研究分析。</p><a href="${source}" target="_blank" rel="noopener">固定版本目录 ↗</a><a href="https://agentskills.io/specification" target="_blank" rel="noopener">技能格式规范 ↗</a><a href="https://github.com/yydshly/0929_codex_project/tree/main/projects/001-awesome-agent-skills" target="_blank" rel="noopener">完整研究文档 ↗</a><a href="./UPSTREAM-LICENSE.txt">目录 MIT 许可</a></section></main><footer>开源项目研究 · 001 / Awesome Agent Skills <span>原创中文分析与摘要图 · 技能实际效果未实测</span></footer></body></html>`;
 const publish=path.resolve(root,'../../../site/001-awesome-agent-skills');
 for(const dir of [root,path.join(root,'dist'),publish]){
  fs.writeFileSync(path.join(dir,'index.html'),html);
  if(dir!==root)fs.copyFileSync(path.join(root,'overview.css'),path.join(dir,'overview.css'));
 }
 for(const dir of [path.join(root,'dist'),publish,path.resolve(root,'../assets')])fs.writeFileSync(path.join(dir,dir.endsWith('assets')?'capability-summary.svg':'summary.svg'),svg);
 console.log(JSON.stringify({summaryDirections:topics.length,scenarios:scenarios.length,summarySvg:'1440 × 1550'}));
}
