import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { renderScope, behavior } from './scope.mjs';
import { renderSummary, summaryDescription } from './summary.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const destination = path.resolve(root, '../../site/006-jakubkrehel-skills');
const sha = '267330e1adfc66a718fb65fa6918c1f06d0a689e';
const upstream = `https://github.com/jakubkrehel/skills/blob/${sha}/`;
const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline = s => escape(s).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
const capabilities = await readFile(path.join(root, 'CAPABILITIES.md'), 'utf8');
const quick = capabilities.split('## 快速选择')[1].split('<a id=')[0].split('\n').filter(l => /^\| [a-z]/.test(l)).map(l => l.split('|').slice(1,-1).map(v=>v.trim()));
const skills = capabilities.split(/^## \d+\. /m).slice(1).map((section, i) => {
  const [id,title] = section.split('\n')[0].split(' · ');
  const field = label => section.match(new RegExp(`\\*\\*${label}：\\*\\* ([^\\n]+)`))?.[1] ?? '';
  const table = section.match(/^\| 具体能力 \|.*(?:\n\|.*)+/m)?.[0];
  const rows = table.split('\n').slice(2).map(l=>l.split('|').slice(1,-1).map(v=>v.trim()));
  const category = ['better-interface','interface-review'].includes(id) ? 'review' : ['break','variant','explain-interface'].includes(id) ? 'explore' : 'domain';
  return {id,title,index:i+1,category,rows,question:quick.find(q=>q[0]===id)?.[1],brief:quick.find(q=>q[0]===id)?.[2],purpose:field('职责'),input:field('需要提供'),output:field('交付物'),example:field('前后示例'),acceptance:field('验收重点'),boundary:field('边界'),prompt:field('示例请求')};
});
if(skills.length!==11 || skills.reduce((n,s)=>n+s.rows.length,0)!==113) throw new Error('Unexpected skill inventory');
const categoryNames = {domain:'专业领域',review:'审查流程',explore:'专项探索'};
const icons = {'better-ui':'◈','better-typography':'Aa','better-colors':'◒','better-accessibility':'◎','better-layout':'▥','better-writing':'¶'};
const rows = skills.map(s=>`<details class="skill" id="${s.id}" data-category="${s.category}"><summary><span class="skill-no">${String(s.index).padStart(2,'0')}</span><span class="skill-heading"><span class="code-name">${s.id}</span><strong>${s.title}</strong><span class="skill-question">${s.question}</span></span><span class="skill-info"><span class="tag">${categoryNames[s.category]}</span><span>${s.rows.length} 项能力</span></span><span class="expand" aria-hidden="true">＋</span></summary><div class="skill-body"><p class="purpose">${inline(s.purpose)}</p><div class="skill-behavior"><span>${behavior[s.id][0]}</span><strong>${behavior[s.id][1]}</strong></div><div class="io-grid"><div><span class="eyebrow">需要提供</span><p>${inline(s.input)}</p></div><div><span class="eyebrow">交付成果</span><p>${inline(s.output)}</p></div></div><h4>具体能力 → 实现方法 → 可观察效果</h4><div class="cap-table"><table><thead><tr><th>具体能力</th><th>如何处理</th><th>可以达到的效果</th></tr></thead><tbody>${s.rows.map(r=>`<tr>${r.map((cell,j)=>`<td data-label="${['能力','做法','效果'][j]}">${inline(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="example"><span class="eyebrow">把能力放进实际问题</span><p>${inline(s.example)}</p></div><div class="io-grid checks"><div><h4>如何验收</h4><p>${inline(s.acceptance)}</p></div><div><h4>能力边界</h4><p>${inline(s.boundary)}</p></div></div><div class="prompt"><span class="eyebrow">可以这样提出任务</span><p>${inline(s.prompt)}</p></div><a class="source-link" href="${upstream}skills/${s.id}/SKILL.md" target="_blank" rel="noopener">核对固定版本原文 ↗</a></div></details>`).join('');
const scenarios = [
 ['01','页面能用，细节却粗糙','账户设置页','先检查整个操作流程，再分别处理键盘障碍、文案和窄屏布局，最后打磨图标与动画。',['better-interface','better-accessibility','better-writing','better-layout','better-ui'],'按影响排序的问题清单；明确要求后实施修复。','键盘能走完整个流程，窄屏不丢操作，错误提示有可执行的下一步。'],
 ['02','重构有没有把界面改坏？','共享按钮 / PR','对比修改前后，查看删除的标签、焦点和状态提示，确认是否存在等效替代。',['interface-review'],'区分新增、退化和历史问题的报告。','每个退化都有旧版依据，历史问题不混入本次修改结论。'],
 ['03','接入真实内容会不会撑坏？','标签列表 / 表格','把空数据、超长名称、大量条目和窄容器放在同一场景页，观察真实组件。',['break'],'可以逐项查看的场景页和破损标注。','实际导入项目组件；只把已观察的失败列为发现。'],
 ['04','三个设计方向怎么选？','仪表盘指标卡','围绕信息密度制作宽松、均衡、紧凑三版，保持同一数据，在实际页面里全尺寸比较。',['variant'],'可切换候选、方案链接和取舍表。','各方案可运行且满足共同底线；选中后落地并清理其他候选。'],
 ['05','参考网站的光晕怎么做？','渐变 / 动画效果','检查元素、伪元素、渐变、模糊与遮罩，按绘制顺序说明每层在视觉上做了什么。',['explain-interface'],'图层机制说明、关键证据和可迁移配方。','实测与推断分开；截图不能证明原作者的代码与框架。'],
 ['06','深色主题为什么看不清？','颜色系统','追踪文字与背景的真实颜色组合，检查语义变量是否用错，修复后分别测量两种主题。',['better-colors','better-accessibility'],'变量关系、失败颜色对和修复后的测量记录。','测的是组件实际背景；共享变量的其他使用位置也要复核。']
];
const research = await readFile(path.join(root, 'RESEARCH.md'), 'utf8');
const extensions = research.split('## 可扩展方向')[1].split('建议先')[0].split('\n').filter(l=>l.startsWith('| ')&&!l.startsWith('| 方向')&&!l.startsWith('| ---')).map(l=>l.split('|').slice(1,-1).map(v=>v.trim()));
const skillLinks = ids => ids.map(id=>`<a class="skill-chip" href="#${id}">${id}</a>`).join('');
const {scope,chooser,faq} = renderScope({inline,skillLinks,upstream});
const {summary,personalSection} = renderSummary({skillLinks});
const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${summaryDescription}"><title>界面如何变得更好 · Jakub Krehel Skills 研究</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='9' fill='%23243730'/%3E%3Ctext x='20' y='28' text-anchor='middle' font-size='26' fill='%23e4eead'%3Ei%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="scope.css"><link rel="stylesheet" href="summary.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#main">跳到内容</a><header class="topbar"><a class="brand" href="#"><span class="brand-symbol">i.</span>INTERFACE NOTES <span class="edition">/ 006</span></a><nav aria-label="章节导航"><a href="#summary">摘要</a><a href="#scope">范围</a><a href="#choose">选用</a><a href="#skills">技能</a><a href="#effects">效果</a><a href="#personal">我的场景</a><a href="#mechanism">原理</a><a href="#extensions">扩展</a></nav><a class="repo-link" href="https://github.com/jakubkrehel/skills" target="_blank" rel="noopener">原仓库 ↗</a></header>
<main id="main"><section class="hero wrap" id="overview"><div class="hero-copy"><p class="eyebrow"><span class="tiny-square"></span> 开源项目研究 · JAKUB KREHEL / SKILLS</p><h1>专注界面质量的<br>AI 技能集。</h1><p class="intro">6 个专业领域 + 5 种工作流程。<br>从视觉、布局和文案，到交互可用性、审查与方案探索。</p><div class="hero-actions"><a class="button primary" href="#summary">先看能力与效果 <span>↘</span></a><a class="text-link" href="#personal">对我有什么用 →</a></div><p><a class="text-link" href="capability-map.html">一张图看懂全部能力 · 放大阅读与下载 →</a></p><p class="version">固定版本 <code>267330e</code> · 研究更新于 2026.09.29</p></div><div class="hero-board"><div class="board-label"><span>FROM RULES TO RESULTS</span><span>01—11</span></div><div class="board-stack"><div class="board-row"><span class="board-mark">01</span><div><strong>先看见问题</strong><p>审查页面、定位退化、观察边界状态</p></div><span class="board-arrow">↗</span></div><div class="board-row"><span class="board-mark">02</span><div><strong>再选择改法</strong><p>六个专业领域，共同支撑判断</p></div><span class="board-arrow">↗</span></div><div class="board-row highlight"><span class="board-mark">03</span><div><strong>让结果可以验证</strong><p>报告 · 代码修复 · 场景页 · 候选方案</p></div><span class="board-arrow">↗</span></div></div><div class="board-foot"><span class="dot"></span>规则由模型理解，动作由宿主工具执行。</div></div></section>
<div class="metrics wrap"><div><strong>11<span>项</span></strong><p>完整技能逐项拆解</p></div><div><strong>113<span>条</span></strong><p>研究归纳的能力与效果</p></div><div><strong>6<span>个</span></strong><p>从问题出发的使用场景</p></div><div class="metric-note"><span class="eyebrow">阅读前提</span><p>本页基于固定版本文档研究。<br>效果是预期目标，示例不是技能实测。</p></div></div>
${summary}
${personalSection}
${scope}
${chooser}
<section class="section wrap" id="map"><div class="section-head"><div><p class="eyebrow">01 / CAPABILITY MAP</p><h2>六个领域，五种工作流程。</h2></div><p>专业技能提供判断依据，工作流程组织任务。<br>从你要解决的问题进入，不必一次使用全部技能。</p></div><div class="domain-grid">${skills.filter(s=>s.category==='domain').map(s=>`<a class="domain-tile" href="#${s.id}"><span class="domain-icon">${icons[s.id]}</span><h3>${s.title.split(' · ')[0]}</h3><p>${s.question}</p><span class="tile-bottom">${s.id}<span>↗</span></span></a>`).join('')}</div><div class="workflow-strip"><span>工作流程</span>${skills.filter(s=>s.category!=='domain').map(s=>`<a href="#${s.id}">${s.title.replace('跨领域界面审查','整体审查').replace('代码变更的界面影响审查','变更审查').replace('网页实现机制解析','实现解析').replace('组件极端场景展示与观察','场景观察').replace('可运行的组件设计候选','方案探索')}<small>${s.id}</small></a>`).join('')}</div></section>
<section class="library section" id="skills"><div class="wrap"><div class="section-head"><div><p class="eyebrow">02 / SKILL LIBRARY</p><h2>每个技能，具体能做什么？</h2></div><p>展开一项，查看能力、方法、效果与验收。<br>搜索会同时检索详细能力和实际例子。</p></div><div class="library-toolbar"><div class="search-box"><span aria-hidden="true">⌕</span><label class="sr-only" for="search">搜索技能、问题或效果</label><input id="search" type="search" placeholder="试试：长文本、键盘、颜色、动画…" autocomplete="off"><kbd>/</kbd></div><div class="filters" role="group" aria-label="技能类型"><button type="button" data-filter="all" aria-pressed="true">全部 <span>11</span></button><button type="button" data-filter="domain" aria-pressed="false">专业领域 <span>6</span></button><button type="button" data-filter="review" aria-pressed="false">审查流程 <span>2</span></button><button type="button" data-filter="explore" aria-pressed="false">专项探索 <span>3</span></button></div></div><div class="results-line"><p id="results" role="status" aria-live="polite">显示 11 个技能 · 113 条能力</p><button id="reset" type="button" hidden>清除筛选</button></div><div class="skill-list">${rows}</div><div class="empty" id="empty" hidden><h3>没有找到匹配的技能</h3><p>试着换成具体问题，例如“换行”“焦点”或“深色”。</p><button type="button" class="button" id="empty-reset">查看全部技能</button></div><noscript><p>当前未启用 JavaScript，仍可展开并阅读全部技能。</p></noscript></div></section>
${faq}
<section class="section wrap" id="effects"><div class="section-head"><div><p class="eyebrow">03 / VISIBLE OUTCOMES</p><h2>把“变好”说得更具体。</h2></div><p>下面是研究构造的说明性示例，<br>帮助理解目标效果，不是上游技能运行记录。</p></div><div class="effect-grid"><article class="effect-card"><div class="effect-title"><span>01</span><h3>长内容，仍然读得完整</h3></div><div class="sample before"><small>修改前 · 信息被截断</small><p class="clipped">2026 年第三季度品牌设计规范与交互组件更新记录</p></div><div class="sample after"><small>目标效果 · 可查看完整内容</small><details class="sample-detail"><summary>2026 年第三季度品牌设计规范… <span>展开</span></summary><p>2026 年第三季度品牌设计规范与交互组件更新记录</p></details></div><p class="effect-explain">保留紧凑布局，同时为重要的完整内容提供可达入口。</p>${skillLinks(['better-typography','better-layout'])}</article><article class="effect-card"><div class="effect-title"><span>02</span><h3>失败之后，有路可走</h3></div><div class="sample before"><small>修改前 · 只有结果</small><p>出错了。</p></div><div class="sample after"><small>目标效果 · 下一步明确</small><p><b>保存失败</b><br>检查网络连接后重试。</p></div><p class="effect-explain">恢复建议必须符合真实能力；改写文案不会自动增加重试功能。</p>${skillLinks(['better-writing'])}</article><article class="effect-card"><div class="effect-title"><span>03</span><h3>状态，不只靠颜色表达</h3></div><div class="sample before"><small>修改前 · 只显示绿色</small><p><span class="status-dot"></span><span class="sr-only">绿色状态点</span></p></div><div class="sample after"><small>目标效果 · 文字与图标共同表达</small><p class="success"><span aria-hidden="true">✓</span> 已保存</p></div><p class="effect-explain">即使难以分辨颜色，也能理解状态；动态播报仍需单独实现与验证。</p>${skillLinks(['better-accessibility','better-colors'])}</article></div><div class="takeaway"><strong>先分清交付，再判断效果。</strong><p>审查交付报告；明确要求修复才改代码。<code>break</code> 交付场景页，<code>variant</code> 交付候选，<code>explain-interface</code> 交付机制解释。</p></div></section>
<section class="section scenario-section" id="scenarios"><div class="wrap"><div class="section-head"><div><p class="eyebrow">04 / IN PRACTICE</p><h2>从正在遇到的问题出发。</h2></div><p>六种典型任务，从输入到交付，<br>都把“怎么确认有效”放在最后一步。</p></div><div class="scenario-grid">${scenarios.map(s=>`<article class="scenario"><div class="scenario-top"><span>${s[0]}</span><span>${s[2]}</span></div><h3>${s[1]}</h3><p>${s[3]}</p><div class="scenario-skills">${skillLinks(s[4])}</div><details><summary>查看交付与验收 <span aria-hidden="true">＋</span></summary><dl><dt>得到什么</dt><dd>${s[5]}</dd><dt>如何确认</dt><dd>${s[6]}</dd></dl></details></article>`).join('')}</div></div></section>
<section class="section wrap" id="mechanism"><div class="section-head"><div><p class="eyebrow">05 / HOW IT WORKS</p><h2>设计知识，如何变成行动？</h2></div><p>核心是可执行的工作规范。<br>模型解释规则，宿主提供代码与浏览器工具。</p></div><ol class="pipeline"><li><span>01</span><h3>识别任务</h3><p>从问题进入对应技能</p></li><li><span>02</span><h3>读取规则</h3><p>技能正文与参考配方</p></li><li><span>03</span><h3>理解项目</h3><p>组件、变量、现有规范</p></li><li><span>04</span><h3>执行与观察</h3><p>读代码、操作或修改</p></li><li><span>05</span><h3>交付与验证</h3><p>结果、证据、未验证项</p></li></ol><div class="mechanism-grid"><article><h3>知识层：各自负责</h3><p>布局管空间，排版管文字显示，文案管措辞。跨领域问题按根因归属，避免重复报告。</p></article><article><h3>流程层：组织判断</h3><p>限定范围、分类问题、排序和汇总。先解决阻断任务的问题，再处理视觉细节。</p></article><article><h3>工具层：提供证据</h3><p>源码可检查规则；浏览器确认真实呈现。没有执行的检查，必须标记为未验证。</p></article></div><div class="boundary"><h3>理解它的边界</h3><p>这些技能以文档为主，不自带独立检测引擎。安装不会改变模型参数，也不自动保证界面质量、合规或转化提升。实际效果依赖模型能力、项目条件与验证。</p><p><code>interface-review</code>、<code>break</code>、<code>variant</code>、<code>explain-interface</code> 在上游配置中要求用户主动调用。</p></div></section>
<section class="section extension-section" id="extensions"><div class="wrap"><div class="section-head"><div><p class="eyebrow">06 / WHAT COMES NEXT</p><h2>让规则更贴近自己的项目。</h2></div><p>以下是研究提出的扩展方向，<br>不代表仓库已经实现这些功能。</p></div><div class="extension-grid">${extensions.map((r,i)=>`<article><span class="extension-no">${String(i+1).padStart(2,'0')}</span><h3>${r[0]}</h3><p>${r[1]}</p><details><summary>预期价值与验证</summary><p><b>价值：</b>${r[2]}</p><p><b>验证：</b>${r[3]}</p></details></article>`).join('')}</div><p class="roadmap">建议顺序 <span>团队规则</span><b>→</b><span>可测量的工具</span><b>→</b><span>回归与评估样例</span></p></div></section>
<footer class="wrap"><div><a class="brand" href="#">INTERFACE NOTES <span class="edition">/ 006</span></a><p>读懂能力，也读懂结果成立的条件。</p></div><div class="footer-meta"><p>资料依据：11 个技能 · 35 份辅助参考 · 固定提交 267330e</p><p>来源采用 MIT 许可 · 中文整理与示例为独立研究</p><a href="${upstream}README.md" target="_blank" rel="noopener">查看上游文档 ↗</a><a href="../index.html">返回研究集 →</a></div></footer></main></body></html>`;
await mkdir(destination, { recursive:true });
for(const dir of [here,destination]) await writeFile(path.join(dir,'index.html'),dir===here?html.replace('href="../index.html">返回研究集','href="../../../site/index.html">返回研究集'):html,'utf8');
for(const file of ['styles.css','scope.css','summary.css','app.js','capability-map.html','capability-map.png','capability-map.svg']) await copyFile(path.join(here,file),path.join(destination,file));
await writeFile(path.join(here,'catalog.json'),JSON.stringify(skills,null,2)+'\n','utf8');
console.log(JSON.stringify({skills:skills.length,capabilities:skills.reduce((n,s)=>n+s.rows.length,0),scenarios:scenarios.length,extensions:extensions.length,destination},null,2));
